create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  borrower_type text not null check (borrower_type in ('seat', 'manager')),
  borrower_id bigint not null,
  principal_amount numeric not null,
  duration_months integer not null,
  installment_frequency text not null check (
    installment_frequency in ('monthly', 'quarterly', 'semi_annual')
  ),
  expected_installment_amount numeric not null,
  start_date timestamptz not null,
  status text not null default 'active' check (status in ('active', 'completed')),
  total_paid numeric not null default 0,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.loan_payments (
  id bigint generated by default as identity primary key,
  loan_id bigint not null references public.loans(id) on delete restrict,
  amount numeric not null,
  paid_at timestamptz not null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists loans_borrower_idx
  on public.loans (borrower_type, borrower_id);

create index if not exists loan_payments_loan_id_idx
  on public.loan_payments (loan_id);

create index if not exists loan_payments_paid_at_idx
  on public.loan_payments (paid_at);
